[environment]
id = "pr-service-b-4"

[components.service-a]
follow = "dev"

[components.service-b]
repo = "henosis-playground/service-b"
ref = "poc/20260708-c5-service-b-second"
digest = "sha256:eda910454022f41bb7697b0b47e49340245345ff5f76724e3db459ac13b05ec9"
