[environment]
id = "preview-3daf152b-7a0c-4c35-ab8b-a21f3eef22d4"

[components.service-a]
follow = "dev"

[components.service-b]
repo = "henosis-playground/service-b"
ref = "MikeIvanichev-patch-1"
digest = "sha256:88a6df80e8048418b6f4e682453a72112690e7b35b118f64a47d43c9e0b7c1e2"
