[environment]
id = "preview-test-2"

[components.service-a]
repo = "henosis-playground/service-a"
ref = "MikeIvanichev-patch-2"
digest = "sha256:578ec8f54ee36aa434c00cceec9dfb5f354d197e4561e58cd2d3df0410cac543"

[components.service-b]
repo = "henosis-playground/service-b"
ref = "MikeIvanichev-patch-2"
digest = "sha256:2040b2de763dbc09c279542d9dc04687e458ff25955cbe113fe9f4078b906e3a"
