[environment]
id = "preview-e32f8600-f61f-41f2-bee7-65c8d998ea1c"

[components.service-a]
follow = "dev"

[components.service-b]
repo = "henosis-playground/service-b"
ref = "d20-consume-port-output"
digest = "sha256:427f71373b7dc4798824a9019b7c5d5dfbd7424145472dc02659cccd1fed731c"
