---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: service-a
  labels:
    henosis.dev/graph-id: graph_01kxqqcfdaf7gbef3h9d94rzzc
    henosis.dev/resource-id: resource_3w3wksptx96rh36j92qz1h1ndm
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: api
  type: ClusterIP
