---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: service-b
  labels:
    henosis.dev/graph-id: graph_01kxqqcfdaf7gbef3h9d94rzzc
    henosis.dev/resource-id: resource_5a6j547y307b2r9senhwn67740
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: app
  type: ClusterIP
