schema = 1
graph = "graph_01kxknzjgae2svcyq8abk781ey"
name = "dev"
generation = 1

[[components]]
name = "service-a"
bundleDigest = "vDaeqEwnMpa39kd8WhHENsd4pa6o7Ia0G2gxI63MB2c="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-a"
revision = "93c8f044d2f6464d5f9345fa778ba34c92d99544"
ref = "refs/heads/d26-live-baseline"

[[components]]
name = "service-b"
bundleDigest = "KnfXtOwo0Y9hpkLbxJRC2RvrUSaQT6CH+Kw3ZWlGqeo="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-b"
revision = "4b5b3c8af620a78eb9eab508e5c33e8f95514e93"
ref = "refs/heads/d26-live-baseline"

[[components]]
name = "service-d"
bundleDigest = "Qh88B6Nq/UbUpri2LwDo7H+1+208JtHUczZ/aXLGv28="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-d"
revision = "c70c724c0382fd5c806e5a2b98b1dd24645f98e2"
ref = "refs/heads/d26-live-baseline"

[[components]]
name = "service-e"
bundleDigest = "RI01S1iEybmIUHbLqzalEm4r4SXnUy81QHkfYkWpe88="

inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-e"
revision = "0842b194c3b710053231e0df61fa862044f59b8b"
ref = "refs/heads/d26-live-skew-consumer"

[[components]]
name = "service-f"
bundleDigest = "d65PjP3JYayrvv+ppnfzS+wA0uoPrH4bVtJWxEsdYcM="

inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-f"
revision = "2dcb7231401878e0383ad40c4962c334faa5797c"
ref = "refs/heads/d26-live-baseline"
