schema = 1
graph = "graph_01kxmbsertfy0va00vfy6wenbm"
name = "preview"
generation = 1

[[components]]
name = "service-a"
bundleDigest = "vDaeqEwnMpa39kd8WhHENsd4pa6o7Ia0G2gxI63MB2c="
inputBindings = []

[components.source]
kind = "vcs"
repository = "https://github.com/henosis-playground/service-a.git"
revision = "93c8f044d2f6464d5f9345fa778ba34c92d99544"
ref = "origin/d26-live-baseline"
