schema = 1
graph = "graph_01kxknzjgae2svcyq8abk781ey"
name = "dev"
generation = 7

[[components]]
name = "service-a"
bundleDigest = "vDaeqEwnMpa39kd8WhHENsd4pa6o7Ia0G2gxI63MB2c="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-a"
revision = "93c8f044d2f6464d5f9345fa778ba34c92d99544"
ref = "refs/heads/main"

[[components]]
name = "service-b"
bundleDigest = "EJx3FoWCN/qJ6+9hTMEYs2s2qWC1WNkXXqa7CihR/KU="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-b"
revision = "4b5b3c8af620a78eb9eab508e5c33e8f95514e93"
ref = "refs/heads/main"

[[components]]
name = "service-d"
bundleDigest = "Qh88B6Nq/UbUpri2LwDo7H+1+208JtHUczZ/aXLGv28="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-d"
revision = "c70c724c0382fd5c806e5a2b98b1dd24645f98e2"
ref = "refs/heads/main"

[[components]]
name = "service-e"
bundleDigest = "dYkYhLh0ZYOyewgfmrdIk4eUe8pQ47lht8R3QHQsfwY="

[[components.inputBindings]]
name = "workerEntry"
valueJson = "InNoYTI1Njo1M2E4OTFmZGFlNzFkYjI0YTA5MmI1N2I2M2UwODcxYzdkMjNjNmFhNTA2MTk1YTgyN2M1OTQwYTQyMTM2NWM4Ig=="

[components.source]
kind = "vcs"
repository = "henosis-playground/service-e"
revision = "0842b194c3b710053231e0df61fa862044f59b8b"
ref = "refs/heads/main"

[[components]]
name = "service-f"
bundleDigest = "OfrqPB0Y6hT5XKSQizYPBBkuYjKUWe/ja6yQ6iV7T5Y="

[[components.inputBindings]]
name = "workerAssets"
valueJson = "InNoYTI1NjoxNmE3YjUyNjJmNTExZWM1ODMxODA1NGM1MjQ0ZDJiMDgxMjIzZDgyY2YzZWQ4NmI4ZDUyZDNlNTVkMzcwY2E4Ig=="

[[components.inputBindings]]
name = "workerEntry"
valueJson = "InNoYTI1NjoxMTAzOGVjNjgyYTQ1YWU3YTFlMWE3YTM5MGVkMTc2NmM3YTdjODJiMmY0Y2Q1NWVjNGQyZDZhNDdhNzUyNDc1Ig=="

[components.source]
kind = "vcs"
repository = "henosis-playground/service-f"
revision = "2dcb7231401878e0383ad40c4962c334faa5797c"
ref = "refs/heads/main"
