schema = 1
graph = "graph_01kxqqcfdaf7gbef3h9d94rzzc"
name = "dev"
generation = 4

[[components]]
name = "service-a"
bundleDigest = "vDaeqEwnMpa39kd8WhHENsd4pa6o7Ia0G2gxI63MB2c="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-a"
revision = "aab579ff16d67b4706d03936871163aded14516a"
ref = "refs/heads/main"

[[components]]
name = "service-b"
bundleDigest = "EJx3FoWCN/qJ6+9hTMEYs2s2qWC1WNkXXqa7CihR/KU="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-b"
revision = "d6dc64c9eeb253a62ca9d62c55fcd53b8e270d66"
ref = "refs/heads/main"

[[components]]
name = "service-d"
bundleDigest = "Qh88B6Nq/UbUpri2LwDo7H+1+208JtHUczZ/aXLGv28="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-d"
revision = "057c85d18e1ccfbf5b7d32c4858edf58c9095c6f"
ref = "refs/heads/main"

[[components]]
name = "service-e"
bundleDigest = "dYkYhLh0ZYOyewgfmrdIk4eUe8pQ47lht8R3QHQsfwY="

[[components.inputBindings]]
name = "workerEntry"
valueJson = "InNoYTI1Njo1M2E4OTFmZGFlNzFkYjI0YTA5MmI1N2I2M2UwODcxYzdkMjNjNmFhNTA2MTk1YTgyN2M1OTQwYTQyMTM2NWM4Ig=="

[components.source]
kind = "vcs"
repository = "henosis-playground/service-e"
revision = "70125ae3caa352481fe4f6ec2baea14ed3ced6cd"
ref = "refs/heads/main"
