schema = 1
graph = "graph_01kxqr26c2f8sv672tjzp99457"
name = "preview"
generation = 1

[[components]]
name = "service-a"
bundleDigest = "vDaeqEwnMpa39kd8WhHENsd4pa6o7Ia0G2gxI63MB2c="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-a"
revision = "aab579ff16d67b4706d03936871163aded14516a"

[[components]]
name = "service-b"
bundleDigest = "pCaq0RewTJCCbA2w6UoM97omS2jlD0aOP2PLs9hBYqs="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-b"
revision = "a68263150aea2e452a5eeb79a2fbc6f98f8f1af0"
ref = "refs/heads/demo/compatible-observability"
