schema = 1
graph = "graph_01kxmcd3z1fbgb6r2jffmvz68k"
name = "d26-skew-acceptance"
generation = 2

[[components]]
name = "service-a"
bundleDigest = "T88c4AAAOKw1Qqu5vpz6TgThWOzjV/X2jduMn8mZDx8="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-a"
revision = "a4e95b70b0c7b1807dd7174a2518c18e5181ff01"
