schema = 1
graph = "graph_01kxkmn9j2ewsb3gyxmt686wxc"
name = "dev"
generation = 1

[[components]]
name = "service-a"
bundleDigest = "BAwdnPLVEJy/XG0PUg7bynKqRceOGeE/XCgQZd+yQyY="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-a"
revision = "5ce78c6d985dca18a0beacba0376053e5f5effd7"
ref = "refs/heads/main"
