schema = 1
graph = "graph_01kxkp2pypf909r9k5045awjd0"
name = "shared-af-cycle-1"
generation = 3

[[components]]
name = "service-a"
bundleDigest = "BAwdnPLVEJy/XG0PUg7bynKqRceOGeE/XCgQZd+yQyY="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-a"
revision = "d02af85070981537869fe305a7696650614d32ed"

[[components]]
name = "service-d"
bundleDigest = "RSe+DZZvWiX8ofu60MqBQTier/jOhL4bXl7BIryZ57o="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-d"
revision = "3a48ee15424d98a783fa59a80a6adcd8423b3933"

[[components]]
name = "service-e"
bundleDigest = "uV8zhH9lD5rGnZX90txlG/jsQbI35Vb80SOLbWUGQj4="

[[components.inputBindings]]
name = "workerArtifact"
valueJson = "InNoYTI1Njo2MjRhZDViNTYxYjJjMzU2MmNiNTIzNjRkNWFmMjkyNDAyZWM3MGM0MzI1NDQ1MDRkMjIwZDAwZTExNjE3N2U5Ig=="

[components.source]
kind = "vcs"
repository = "henosis-playground/service-e"
revision = "8f557fd14d16148285a667971be883e9819c661d"
