schema = 1
graph = "graph_01kxknzjgae2svcyq8abk781ey"
name = "dev"
generation = 4

[[components]]
name = "service-a"
bundleDigest = "BAwdnPLVEJy/XG0PUg7bynKqRceOGeE/XCgQZd+yQyY="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-a"
revision = "d02af85070981537869fe305a7696650614d32ed"
ref = "refs/heads/main"

[[components]]
name = "service-b"
bundleDigest = "Qee+v0SjRORyp684OI33VVzYlo/4E/jMiZQQe4/oqls="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-b"
revision = "674e225ea89d10324be548b86c0ff6de63fb6a04"
ref = "refs/heads/main"

[[components]]
name = "service-d"
bundleDigest = "RSe+DZZvWiX8ofu60MqBQTier/jOhL4bXl7BIryZ57o="
inputBindings = []

[components.source]
kind = "vcs"
repository = "henosis-playground/service-d"
revision = "3a48ee15424d98a783fa59a80a6adcd8423b3933"
ref = "refs/heads/main"

[[components]]
name = "service-e"
bundleDigest = "uV8zhH9lD5rGnZX90txlG/jsQbI35Vb80SOLbWUGQj4="

[[components.inputBindings]]
name = "workerArtifact"
valueJson = "InNoYTI1Njo1M2E4OTFmZGFlNzFkYjI0YTA5MmI1N2I2M2UwODcxYzdkMjNjNmFhNTA2MTk1YTgyN2M1OTQwYTQyMTM2NWM4Ig=="

[components.source]
kind = "vcs"
repository = "henosis-playground/service-e"
revision = "f15d2da8c2e846a6bf4a4890990c5f890a088eb7"
ref = "refs/heads/main"
